const capitals = [
  'Amsterdam',
  'Athens',
  'Belgrade',
  'Berlin',
  'Bratislava',
  'Brussels',
  'Bucharest',
  'Budapest',
  'Copenhagen',
  'Dublin',
  'Helsinki',
  'Lisbon',
  'Ljubljana',
  'London',
  'Luxembourg',
  'Madrid',
  'Moscow',
  'Oslo',
  'Paris',
  'Prague',
  'Riga',
  'Rome',
  'Sarajevo',
  'Skopje',
  'Sofia',
  'Stockholm',
  'Vienna',
  'Warsaw',
  'Zagreb',
]

module.exports.getRandomEuCapital = () => capitals[global.getRandomInt(capitals.length)]